### ISSUE TITLE
APP CRASHED

### ISSUE THREAD

**Issue by sidanya** [forscht/ddrive#14]
I am trying to run this command but it does not work

`ddrive --token {{valid token}} --channelId {{valid channel id}}`
  
error log:
```
  discordFS >>> booting discordFS +0ms
  app === APP CRASHED :: UNKNOWN ERROR === 
  app  TypeError: Cannot read properties of undefined (reading 'type')
    at /usr/lib/node_modules/@forscht/ddrive/src/discordFS/index.js:77:94
    at arrayAggregator (/usr/lib/node_modules/@forscht/ddrive/node_modules/lodash/lodash.js:511:34)
    at Function.groupBy (/usr/lib/node_modules/@forscht/ddrive/node_modules/lodash/lodash.js:4885:16)
    at DiscordFS.load (/usr/lib/node_modules/@forscht/ddrive/src/discordFS/index.js:77:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startApp (/usr/lib/node_modules/@forscht/ddrive/bin/ddrive:51:5) +0ms
```

**Comment by darshan-genea** [comment]
@idanyas There must be messages in channel which are not created by bot, delete those messages

**Comment by sidanya** [comment]
> @idanyas There must be messages in channel which are not created by bot, delete those messages

Thanks, it turns out there was a message about the bot entering the server
