### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Mantra27** [forscht/ddrive#32]
ddrive --token MTAxNzQzMTgzNDMzNTkxNjA0Ng.G0Vrdc.hvi10IrwB4Y7SknPsMiXTt1QbRaRyTnX5U4phE --channelId 1017423611138499596

**Comment by Mantra27** [comment]
(node:2427) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  app === APP CRASHED :: UNKNOWN ERROR === 
  app  TypeError: Cannot read properties of undefined (reading 'type')
    at /usr/local/lib/node_modules/@forscht/ddrive/src/discordFS/index.js:78:94
    at arrayAggregator (/usr/local/lib/node_modules/@forscht/ddrive/node_modules/lodash/lodash.js:511:34)
    at Function.groupBy (/usr/local/lib/node_modules/@forscht/ddrive/node_modules/lodash/lodash.js:4885:16)
    at DiscordFS.load (/usr/local/lib/node_modules/@forscht/ddrive/src/discordFS/index.js:78:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startApp (/usr/local/lib/node_modules/@forscht/ddrive/bin/ddrive:62:5)

**Comment by BrainBursty** [comment]
> MTAxNzQzMTgzNDMzNTkxNjA0Ng.G0Vrdc.hvi10IrwB4Y7SknPsMiXTt1QbRaRyTnX5U4phE

Token leaked you should change it! @Mantra27

**Comment by BrainBursty** [comment]
Also your bug comes from the fact that the channel you pointed the bot at contains messages that are not send by the bot.

The bot needs a custom channel only for him, where nobody except the bot posts messages. If someone posts a message in that channel who isn't the bot the bot breaks!

**Comment by Mantra27** [comment]
> > MTAxNzQzMTgzNDMzNTkxNjA0Ng.G0Vrdc.hvi10IrwB4Y7SknPsMiXTt1QbRaRyTnX5U4phE
> 
> Token leaked you should change it! @Mantra27 

Ikr, i already did change it
