### ISSUE TITLE
Throws this Error

### ISSUE THREAD

**Issue by BoKa33** [forscht/ddrive#7]
[bvb@bvbManjLX ~]$ sudo ddrive --token  " **** " --channelId " **** "
  discordFS >>> booting discordFS +0ms
  app === APP CRASHED :: UNKNOWN ERROR === 
  app  TypeError: Cannot read properties of undefined (reading 'type')
    at /usr/lib/node_modules/@forscht/ddrive/src/discordFS/index.js:77:94
    at arrayAggregator (/usr/lib/node_modules/@forscht/ddrive/node_modules/lodash/lodash.js:511:34)
    at Function.groupBy (/usr/lib/node_modules/@forscht/ddrive/node_modules/lodash/lodash.js:4885:16)
    at DiscordFS.load (/usr/lib/node_modules/@forscht/ddrive/src/discordFS/index.js:77:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startApp (/usr/lib/node_modules/@forscht/ddrive/bin/ddrive:51:5) +0ms
[bvb@bvbManjLX ~]$ 

Im using Manjaro, installed newest nodejs version...

**Comment by darshan-genea** [comment]
@BoKa33 Does your channel have messages other than, message created by bot?

**Comment by BoKa33** [comment]
Oh year there are
