### ISSUE TITLE
"404: Not Found","code":0,"reqId":"req-7" every time trying to upload file

### ISSUE THREAD

**Issue by skygunner** [forscht/ddrive#85]
version is current v4 in master repo
node version 18.16.0
any idea what's the cause?

"404: Not Found","code":0,"reqId":"req-7" every time trying to upload file, upload is not successfully, seems not even started uploading at all.

```shell
{"level":30,"time":1682744200221,"reqId":"req-7","req":{"method":"POST","url":"/api/files/75c83136-1a7e-478c-9eb8-2e09b968f837","hostname":"ddrive.test.com:3003","remoteAddress":"158.32.1.2","remotePort":8620},"msg":"incoming request"}
(node:418271) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
    at emitExperimentalWarning (node:internal/util:238:11)
    at new File (node:internal/file:41:5)
    at makeEntry (/home/user1/git/ddrive/node_modules/undici/lib/fetch/formdata.js:242:11)
    at FormData.append (/home/user1/git/ddrive/node_modules/undici/lib/fetch/formdata.js:49:19)
    at RequestManager.resolveRequest (/home/user1/git/ddrive/node_modules/@discordjs/rest/dist/index.js:1213:20)
    at async RequestManager.queueRequest (/home/user1/git/ddrive/node_modules/@discordjs/rest/dist/index.js:1150:35)
    at async REST.request (/home/user1/git/ddrive/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async AsyncStreamProcessorWithConcurrency.processChunk [as chunkProcessor] (/home/user1/git/ddrive/src/DFs/index.js:155:51)
{"level":50,"time":1682744200981,"message":"404: Not Found","code":0,"reqId":"req-7"}
{"level":30,"time":1682744200981,"reqId":"req-7","res":{"statusCode":500},"responseTime":759.7181599959731,"msg":"request completed"}
{"level":30,"time":1682744201005,"reqId":"req-8","req":{"method":"GET","url":"/api/directories/75c83136-1a7e-478c-9eb8-2e09b968f837","hostname":"ddrive.test.com:3003","remoteAddress":"158.32.1.2","remotePort":8620},"msg":"incoming request"}
{"level":30,"time":1682744201010,"reqId":"req-8","res":{"statusCode":200},"responseTime":4.445440001785755,"msg":"request completed"}
```

**Comment by EV0LV3** [comment]
Requirements
NodeJS **v16.x** or Docker

**Comment by forscht** [comment]
Can you try with nodejs 16?

**Comment by drpoutine** [comment]
> Can you try with nodejs 16?

tried with nodejs 16 and im getting this

```
{"level":30,"time":1703562734120,"reqId":"req-1f","req":{"method":"POST","url":"/api/files/3af9ad04-10e3-48d0-a0c6-f60236fdc567","hostname":"0.0.0.0:0000","remoteAddress":"0.0.0.0","remotePort":64389},"msg":"incoming request"}
{"level":50,"time":1703562734227,"message":"404: Not Found","code":0,"reqId":"req-1f"}
{"level":30,"time":1703562734228,"reqId":"req-1f","res":{"statusCode":500},"responseTime":107.53197900019586,"msg":"request completed"}
```
